'use client';
import { FormEvent, useState } from 'react';
import './email-test.css';
const templates = [['registration_confirmation','Conferma registrazione + QR'],['reminder_24h','Reminder 24 ore + QR'],['exit_thank_you','Ringraziamento dopo scan uscita']] as const;
export default function AdminEmailsPage() {
  const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setStatus(''); const data=new FormData(event.currentTarget); const response=await fetch('/api/admin/test-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(data.entries()))}); const result=await response.json().catch(()=>({})); setStatus(response.ok?'Email inviata. Controlla anche la cartella spam.':(result.error||'Invio non riuscito.')); setBusy(false); }
  return <main className="admin"><div className="admin-inner"><div className="eyebrow">DAMAI · Area staff</div><h1>Test email</h1><p>Invia un messaggio di prova usando il template reale. Non crea registrazioni nel database.</p><form className="email-test-form" onSubmit={submit}><label>Template<select name="type" defaultValue="registration_confirmation">{templates.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Email destinatario<input name="email" type="email" required placeholder="tua@email.it" /></label><div className="email-test-grid"><label>Nome<input name="firstName" defaultValue="Antonio" /></label><label>Cognome<input name="lastName" defaultValue="Avella" /></label></div><div className="email-test-grid"><label>Data Open Day<input name="eventDate" type="date" defaultValue="2026-10-30" /></label><label>Orario<input name="startTime" type="time" defaultValue="16:00" /></label></div><label>Codice registrazione<input name="registrationCode" defaultValue="D26-TESTMAIL" /></label><button className="submit" disabled={busy}>{busy?'Invio in corso…':'Invia email di prova'}</button>{status&&<div className="success" role="status">{status}</div>}</form><div className="toolbar"><a href="/admin">← Dashboard</a></div></div></main>;
}
